// mockData/userMetrics.ts
import { UserMetrics } from '@/types/metrics'

export const mockUsersData: Record<string, UserMetrics> = {
  'user-1': {
    userId: 'user-1',
    userName: 'Alice Johnson',
    email: '[REDACTED_EMAIL_ADDRESS_8]',
    copilotUsageHours: 124,
    copilotAcceptanceRate: 85,
    tasksCompleted: 34,
    productivityScore: 8.9,
    codeQualityScore: 9.2,
    timePerTask: 3.6,
    metrics: [
      {
        id: 'metric-user-1-001',
        timestamp: new Date('2024-04-01'),
        value: 85,
        unit: '%',
        category: 'efficiency',
      },
    ],
    trend: 'up',
    trendPercentage: 6.5,
  },
  'user-2': {
    userId: 'user-2',
    userName: 'Bob Smith',
    email: '[REDACTED_EMAIL_ADDRESS_9]',
    copilotUsageHours: 98,
    copilotAcceptanceRate: 78,
    tasksCompleted: 28,
    productivityScore: 8.1,
    codeQualityScore: 8.5,
    timePerTask: 4.2,
    metrics: [
      {
        id: 'metric-user-2-001',
        timestamp: new Date('2024-04-01'),
        value: 78,
        unit: '%',
        category: 'efficiency',
      },
    ],
    trend: 'up',
    trendPercentage: 3.2,
  },
  'user-3': {
    userId: 'user-3',
    userName: 'Carol Davis',
    email: '[REDACTED_EMAIL_ADDRESS_10]',
    copilotUsageHours: 115,
    copilotAcceptanceRate: 88,
    tasksCompleted: 31,
    productivityScore: 9.1,
    codeQualityScore: 9.4,
    timePerTask: 3.4,
    metrics: [
      {
        id: 'metric-user-3-001',
        timestamp: new Date('2024-04-01'),
        value: 88,
        unit: '%',
        category: 'efficiency',
      },
    ],
    trend: 'up',
    trendPercentage: 8.1,
  },
  'user-4': {
    userId: 'user-4',
    userName: 'David Wilson',
    email: '[REDACTED_EMAIL_ADDRESS_11]',
    copilotUsageHours: 102,
    copilotAcceptanceRate: 82,
    tasksCompleted: 26,
    productivityScore: 8.3,
    codeQualityScore: 8.8,
    timePerTask: 4.0,
    metrics: [
      {
        id: 'metric-user-4-001',
        timestamp: new Date('2024-04-01'),
        value: 82,
        unit: '%',
        category: 'efficiency',
      },
    ],
    trend: 'up',
    trendPercentage: 4.5,
  },
  'user-5': {
    userId: 'user-5',
    userName: 'Emma Brown',
    email: '[REDACTED_EMAIL_ADDRESS_12]',
    copilotUsageHours: 110,
    copilotAcceptanceRate: 79,
    tasksCompleted: 29,
    productivityScore: 8.0,
    codeQualityScore: 8.3,
    timePerTask: 4.3,
    metrics: [
      {
        id: 'metric-user-5-001',
        timestamp: new Date('2024-04-01'),
        value: 79,
        unit: '%',
        category: 'efficiency',
      },
    ],
    trend: 'stable',
    trendPercentage: 1.1,
  },
}

export const mockUserWeeklyData = (userId: string) => [
  { name: 'Week 1', tasks: 8, acceptance: 83 },
  { name: 'Week 2', tasks: 9, acceptance: 84 },
  { name: 'Week 3', tasks: 8, acceptance: 86 },
  { name: 'Week 4', tasks: 9, acceptance: 85 },
]

export const mockUserLanguages = (userId: string) => [
  { name: 'TypeScript', value: 40 },
  { name: 'Python', value: 25 },
  { name: 'JavaScript', value: 20 },
  { name: 'Java', value: 10 },
  { name: 'Other', value: 5 },
]

export const mockAllUsers = [
  {
    id: 'user-1',
    name: 'Alice Johnson',
    team: 'Backend Team',
    tasks: 34,
    acceptance: '85%',
    quality: '9.2',
    hours: 124,
    savings: '$12,500',
  },
  {
    id: 'user-2',
    name: 'Bob Smith',
    team: 'Backend Team',
    tasks: 28,
    acceptance: '78%',
    quality: '8.5',
    hours: 98,
    savings: '$9,200',
  },
  {
    id: 'user-3',
    name: 'Carol Davis',
    team: 'Frontend Team',
    tasks: 31,
    acceptance: '88%',
    quality: '9.4',
    hours: 115,
    savings: '$11,800',
  },
  {
    id: 'user-4',
    name: 'David Wilson',
    team: 'Frontend Team',
    tasks: 26,
    acceptance: '82%',
    quality: '8.8',
    hours: 102,
    savings: '$9,800',
  },
  {
    id: 'user-5',
    name: 'Emma Brown',
    team: 'DevOps Team',
    tasks: 29,
    acceptance: '79%',
    quality: '8.3',
    hours: 110,
    savings: '$10,200',
  },
]
